
import java.sql.Connection;
import java.sql.Date;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author acer
 */
public class BiletAl extends javax.swing.JDialog {
   PAUJET islemler =new PAUJET();
   DefaultTableModel model;
   DefaultTableModel model2;
   private Connection con = null;
    private Statement statement = null;
    private PreparedStatement preparedStatement = null;
    GirisEkrani g=new GirisEkrani();
    
    
    /** Creates new form BiletAl */
    public BiletAl(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    
        islemler.listele(cbnereden);
        islemler.listele1(cbnereye);
        model2=(DefaultTableModel) tSefer.getModel();
        model=(DefaultTableModel) tRezervasyon.getModel();
        RezervasyonGoruntule();

        
    }
       public void RezervasyonGoruntule(){
           model.setRowCount(0);
           ArrayList<Rezervasyonlar>rezervasyon=new ArrayList<Rezervasyonlar>();
           rezervasyon =islemler.RezervasyonGetir();
           if(rezervasyon !=null){
               for(Rezervasyonlar rezerve:rezervasyon){
                   Object[] eklenecek={rezerve.getSeferno(),rezerve.getKoltukno(),rezerve.getNereden(),rezerve.getNereye(),rezerve.getTarih(),rezerve.getKacta(),rezerve.getUye()};
                   model.addRow(eklenecek);
               }
           }
       }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layoutStyle1 = new org.jdesktop.layout.LayoutStyle();
        layoutStyle2 = new org.jdesktop.layout.LayoutStyle();
        layoutStyle3 = new org.jdesktop.layout.LayoutStyle();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbnereden = new javax.swing.JComboBox<>();
        cbnereye = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gidist = new javax.swing.JCheckBox();
        seferara = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSefer = new javax.swing.JTable();
        SEFERLER = new java.awt.Label();
        label1 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        tKoltuk = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tRezervasyon = new javax.swing.JTable();
        tgidis = new org.jdesktop.swingx.JXDatePicker();
        tdonus = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        donust = new javax.swing.JCheckBox();
        uyari = new javax.swing.JLabel();
        geri_gel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nereden?");

        jLabel2.setText("Nereye?");

        jLabel3.setText("Gidiş Tarihi");

        jLabel4.setText("Dönüş Tarihi");

        gidist.setText("Gidiş");

        seferara.setText("Sefer Ara");
        seferara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seferaraActionPerformed(evt);
            }
        });

        tSefer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tSefer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSeferMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tSefer);
        if (tSefer.getColumnModel().getColumnCount() > 0) {
            tSefer.getColumnModel().getColumn(0).setResizable(false);
            tSefer.getColumnModel().getColumn(1).setResizable(false);
            tSefer.getColumnModel().getColumn(2).setResizable(false);
            tSefer.getColumnModel().getColumn(3).setResizable(false);
            tSefer.getColumnModel().getColumn(4).setResizable(false);
            tSefer.getColumnModel().getColumn(5).setResizable(false);
        }

        SEFERLER.setText("SEFERLER");

        label1.setText("KOLTUKLAR");

        tKoltuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", " ", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tKoltuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tKoltukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tKoltuk);
        if (tKoltuk.getColumnModel().getColumnCount() > 0) {
            tKoltuk.getColumnModel().getColumn(0).setResizable(false);
            tKoltuk.getColumnModel().getColumn(1).setResizable(false);
            tKoltuk.getColumnModel().getColumn(2).setResizable(false);
        }

        tRezervasyon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tRezervasyon);
        if (tRezervasyon.getColumnModel().getColumnCount() > 0) {
            tRezervasyon.getColumnModel().getColumn(0).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(1).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(2).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(3).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(4).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(5).setResizable(false);
            tRezervasyon.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel5.setText("REZERVASYONLARIM");

        donust.setText("Dönüş");

        geri_gel.setText("GERİ GEL");
        geri_gel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geri_gelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbnereden, 0, 230, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(cbnereye, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(SEFERLER, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seferara)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(donust))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tgidis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addComponent(tdonus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(gidist))
                            .addComponent(uyari))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(geri_gel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geri_gel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(cbnereye, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbnereden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jLabel2))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(uyari)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(gidist))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tgidis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(donust))
                        .addGap(18, 18, 18)
                        .addComponent(tdonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(seferara)
                        .addGap(30, 30, 30)
                        .addComponent(SEFERLER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seferaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seferaraActionPerformed
      java.util.Date date=tgidis.getDate();
        Format formatter=new  SimpleDateFormat("yyyy-MM-dd");
        String date1=formatter.format(date);
        islemler.seferara(tSefer,cbnereden.getSelectedItem().toString(),cbnereye.getSelectedItem().toString(),date1);
       
        
    }//GEN-LAST:event_seferaraActionPerformed

    private void tSeferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSeferMouseClicked
        int index=tSefer.getSelectedRow();
        TableModel model2=tSefer.getModel();
        int seferno=Integer.parseInt(model2.getValueAt(index,0).toString());
        islemler.koltuklar(tKoltuk, seferno);
    }//GEN-LAST:event_tSeferMouseClicked

    private void tKoltukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tKoltukMouseClicked
        int index=tSefer.getSelectedRow();
        TableModel model2=tSefer.getModel();
        int value=tKoltuk.getSelectedRow();
        TableModel table=tKoltuk.getModel();
        int seferno=Integer.parseInt(model2.getValueAt(value,0).toString());
        int koltukno=Integer.parseInt(table.getValueAt(value,0).toString());
        String saat=model2.getValueAt(value,5).toString();
        
        islemler.rezervasyon(tRezervasyon,seferno,koltukno,cbnereden.getSelectedItem().toString(),cbnereye.getSelectedItem().toString(),tgidis.getDate().toString(),saat,GirisEkrani.kullanici_adi);
    }//GEN-LAST:event_tKoltukMouseClicked

    private void geri_gelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geri_gelActionPerformed
        GirisEkrani giris = new GirisEkrani();
        this.setVisible(false);
        giris.setVisible(true);
    }//GEN-LAST:event_geri_gelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiletAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiletAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiletAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiletAl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BiletAl dialog = new BiletAl(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label SEFERLER;
    private javax.swing.JComboBox<String> cbnereden;
    private javax.swing.JComboBox<String> cbnereye;
    private javax.swing.JCheckBox donust;
    private javax.swing.JButton geri_gel;
    private javax.swing.JCheckBox gidist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private org.jdesktop.layout.LayoutStyle layoutStyle1;
    private org.jdesktop.layout.LayoutStyle layoutStyle2;
    private org.jdesktop.layout.LayoutStyle layoutStyle3;
    private javax.swing.JButton seferara;
    private javax.swing.JTable tKoltuk;
    private javax.swing.JTable tRezervasyon;
    private javax.swing.JTable tSefer;
    private org.jdesktop.swingx.JXDatePicker tdonus;
    private org.jdesktop.swingx.JXDatePicker tgidis;
    private javax.swing.JLabel uyari;
    // End of variables declaration//GEN-END:variables

}
